version: '2.1'
services:
    webserver:
        image: registry.dpool.sina.com.cn/sinadbp/docker-airflow.1.10.2
        restart: always
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - /data1/airflow/dags:/data1/airflow/dags
            - /data1/dbatemp/logs/airflow/webserver/logs:/data1/airflow/logs
        ports:
            - "8186:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /data1/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: registry.dpool.sina.com.cn/sinadbp/docker-airflow.1.10.2
        restart: always
        volumes:
            - /data1/dbatemp/logs/airflow/flower/logs:/data1/airflow/logs
        environment:
            - EXECUTOR=Celery
        ports:
            - "8187:5555"
        command: flower

    scheduler:
        image: registry.dpool.sina.com.cn/sinadbp/docker-airflow.1.10.2
        restart: always
        volumes:
            - /data1/airflow/dags:/data1/airflow/dags
            - /data1/dbatemp/logs/airflow/scheduler/logs:/data1/airflow/logs
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
        command: scheduler

    #worker:
    #    image: registry.dpool.sina.com.cn/sinadbp/docker-airflow.1.10.2
    #    restart: always
    #    volumes:
    #        - /data1/airflow/dags:/data1/airflow/dags
    #        - /data1/dbatemp/logs/airflow/worker/logs:/data1/airflow/logs
    #    environment:
    #        - EXECUTOR=Celery
    #    command: worker
