version: '2.1'
services:
    webserver:
        image: puckel/docker-airflow
        restart: always
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - /data1/airflow/dags:/airflow/dags
            - /data1/dbatemp/logs/airflow/webserver/logs:/airflow/logs
        ports:
            - "8186:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: puckel/docker-airflow
        restart: always
        volumes:
            - /data1/dbatemp/logs/airflow/flower/logs:/airflow/logs
        environment:
            - EXECUTOR=Celery
        ports:
            - "8187:5555"
        command: flower

    scheduler:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - webserver
        volumes:
            - /data1/airflow/dags:/airflow/dags
            - /data1/dbatemp/logs/airflow/scheduler/logs:/airflow/logs
        environment:
            - LOAD_EX=n
            - EXECUTOR=Celery
        command: scheduler

    worker:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - scheduler
        volumes:
            - /data1/airflow/dags:/airflow/dags
            - /data1/dbatemp/logs/airflow/worker/logs:/airflow/logs
        environment:
            - EXECUTOR=Celery
        command: worker
