version: '2.1'
services:
    worker2:
        image: puckel/docker-airflow
        restart: always
        volumes:
            - /data1/airflow/dags:/root/airflow/dags
            - /data1/dbatemp/logs/airflow/worker/logs:/root/airflow/logs
        environment:
            - EXECUTOR=Celery
        command: worker
